### ISSUE TITLE
Productionalize the Crawler

### ISSUE THREAD

**Issue by maevyn11** [maevyn11/dsforthepeople#67]
the crawler to a state where it can be run regularly and deliver accumulating value. Development goals include:
- [ ] Generic Link Aggregator plugin capability. Ability to crawl multiple sources aside from nytimes serially and in parallel.
- [ ] Current news capability - Able to crawl archives and current news in compatible formats.
- [x] Instrumentation. Cleanly recorded logs and measurement statistics to promote continuous improvement
- [ ] Testable - Harness to enable continuous improvement and identify external issues. (News source format changes break code)
- [ ] Performance - Efficient code on right sized infrastructure 
- [ ] Robustness - Runs continuously, resilient to failure, minimal maintenance
- [ ] Extensible - Able to support many types of analysis and enable smooth feature additions.

**Comment by michaelgreis** [comment]
Not needed.
