### ISSUE TITLE
Refactor Crawler Design

### ISSUE THREAD

**Issue by maevyn11** [maevyn11/dsforthepeople#89]
Significant performance improvements could be gained by making some changes to the crawler including:
- [ ] Using asynchronous IO through asyncio/aiohttp/requests connection pooling in parsearticle
- [ ] Building the list of article in advance and passing it to parsearticle as a bunch so that persistent connections can be used to amortize the cost of creating connections to the domains. (Discarding the queue based message passing architecture)
- [ ] Using multiprocessing to free the application from it's single core design

**Comment by maevyn11** [comment]
- [ ] Confirm that retry.get did not introduce any bugs that will kill the thread running it

**Comment by maevyn11** [comment]
asyncio may not be worth the trouble. Quick win could be batching up links in each thread so that urllib3's connection pooling can be used.

**Comment by michaelgreis** [comment]
Optimization not needed. If Crawler is going to be used, may need to do this.
